apiVersion: apps/v1
kind: Deployment                 # Deploymentマニフェスト
metadata:
  name: frontend                 # Deploymentリソースの名前
spec:
  selector:
    matchLabels:                 # ReplicaSetが管理(検索)するPodのラベル
      app: guestbook
      tier: frontend
  replicas: 1                    # ReplicaSetが生成・管理するPodの数
  template:                      # ここからPodの定義
    metadata:
      labels:                    # Podのラベル
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis          # コンテナ名
        image: gcr.io/google-samples/gb-frontend:v4  # コンテナイメージ
        resources:               # 使用するCPU, Memoryの指定
          requests:
            cpu: 100m
            memory: 100Mi
        env:                     # 環境変数
        - name: GET_HOSTS_FROM
          value: dns
        ports:                   # EXPOSEするポートの指定
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment                 # Deploymentマニフェスト
metadata:
  name: redis-master             # Deploymentリソースの名前
spec:
  selector:
    matchLabels:                 # ReplicaSetが管理(検索)するPodのラベル
      app: redis
      role: master
      tier: backend
  replicas: 1                    # ReplicaSetが生成・管理するPodの数
  template:                      # ここからPodの定義
    metadata:
      labels:                    # Podのラベル
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master             # コンテナ名
        image: k8s.gcr.io/redis:e2e  # コンテナイメージ
        resources:               # 使用するCPU, Memoryの指定
          requests:
            cpu: 100m
            memory: 100Mi
        ports:                   # EXPOSEするポートの指定
        - containerPort: 6379
---
apiVersion: v1
kind: Service           # Serviceのマニフェスト
metadata:
  name: redis-master    # Service名
  labels:               # Serviceにつけるラベル
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - port: 6379          # Serviceの受け付けるポート
    targetPort: 6379    # コンテナが受け付けるポート
  selector:             # ServiceのターゲットとするPodのラベル
    app: redis
    role: master
    tier: backend
---
apiVersion: apps/v1
kind: Deployment                 # Deploymentマニフェスト
metadata:
  name: redis-slave              # Deploymentリソースの名前
spec:
  selector:
    matchLabels:                 # ReplicaSetが管理(検索)するPodのラベル
      app: redis
      role: slave
      tier: backend
  replicas: 1                    # ReplicaSetが生成・管理するPodの数
  template:                      # ここからPodの定義
    metadata:
      labels:                    # Podのラベル
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave              # コンテナ名
        image: gcr.io/google_samples/gb-redisslave:v1  # コンテナイメージ
        resources:               # 使用するCPU, Memoryの指定
          requests:
            cpu: 100m
            memory: 100Mi
        env:                     # 環境変数
        - name: GET_HOSTS_FROM
          value: dns
        ports:                   # EXPOSEするポートの指定
        - containerPort: 6379
---
apiVersion: v1
kind: Service           # Serviceのマニフェスト
metadata:
  name: redis-slave     # Service名
  labels:               # Serviceにつけるラベル
    app: redis
    role: slave
    tier: backend
spec:
  ports:                # targetPortが省略されている場合はportと同じ値となる
  - port: 6379          # Serviceの受け付けるポート
  selector:             # ServiceのターゲットとするPodのラベル
    app: redis
    role: slave
    tier: backend
